### ISSUE TITLE
Notebook NotJSONError

### ISSUE THREAD

**Issue by ttompost** [NeuroNetMem/assignment4-calcium_imaging_analysis#1]
Dear @melisamc89 ,
I just tried to open _assignment4.ipynb_ Jupyter Notebook and I got stuck with the error shown below:
 
**in my shell:**
`[W 17:42:53.715 NotebookApp] Unreadable Notebook: /Users/teatompos/Desktop/uni/RADBOUD/NeuroAnalysis/assignments/assignment4-calcium_imaging_analysis/assignment4.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')`

**in my browser:**
<img width="712" alt="Slika zaslona 2020-05-28 u 17 43 32" src="https://user-images.githubusercontent.com/48914924/83163955-eeb87680-a10b-11ea-819c-8536e9b7b92a.png">

I cloned this repository and the error occurred upon the first try of opening the notebook. Could I be doing something wrong? Opening notebooks from other assignments does not trigger any errors. 

Best, Tea

**Comment by melisamc89** [comment]
Dear Tea,
 Just solved the problem. Apparently last change I did directly on git and
deleted some fundamental part of the notebook code. The correct file is now
committed.
Best,
Melisa

**Comment by ttompost** [comment]
thanks, it works perfect now! 

Best, Tea
